Fmm restr optimization
alexARC26/FMM pull request #21
Opened 2021-04-26 10:41 UTC by christianco97

### Related with `fitFMM_restr` #5 
* Paralelization working on fitFMM_restr (now: if `parallelize = FALSE` parallelization backend is not registered).
* Internal `fitFMM_restr` functions moved to a new file `FMM_internal_restr`.
* Update documentation (R build checks issues).

### Other changes
* Documentation updated: in `fitFMM`, `parallelize` argument.
* FMM_internal file cleaned (just code annotations).

2021-04-26 10:49 UTC, christianco97 commented
I don't understand the file conflict. Checking later.

2021-04-27 18:03 UTC, alexARC26 requested changes
- [x] Talk about `supressWarnings`.
- [x] Check comments of the PR.
- [x] Check if results coincide with previous versions.

2021-04-27 18:03 UTC, alexARC26 commented on R/FMM_internal.R
> +  for(j in 1:nback){
I know this could prove to be troublesome as this function is used by `optim`, but could this loop be avoided by calling the function `calculateCosPhi` (and multiplying by As)?

2021-04-27 18:03 UTC, alexARC26 commented on R/fitFMM_restr.R
> -
In the documentation of `alphaGrid, omegaGrid` in `fitFMM_restr`: "They can be a list with nback elements, each one for an iteration." (???)

Can this be deleted?

2021-04-27 18:03 UTC, alexARC26 commented on R/fitFMM_restr.R
>    for(j in 1:nback){
See how this is done in `fitFMM_back` to avoid using a for loop.

2021-04-27 18:03 UTC, alexARC26 commented on R/fitFMM_restr.R
>    for(j in 1:nback){
Also, since we are modifying this: use the `as.vector()` in M and A. This prevents that the name of the elements of the vectors are returned.

2021-04-27 18:03 UTC, alexARC26 commented on R/fitFMM_restr.R
I have deleted the line `names(A) <- paste("A", 1:length(A), sep = "")`. All the lines similar should also be deleted: the rest of the parameters are not named (i.e. when getAlpha is used the elements of the vector are not named alpha1, alpha2,...), so its probably best to not name none of them.

2021-04-27 18:03 UTC, alexARC26 commented on R/fitFMM_restr.R
>    if(is.list(alphaGrid)){
This, along with the corresponding lines to `omegaGrid``is used for anything? If deleted, change documentation above.

2021-04-27 18:03 UTC, alexARC26 commented on R/FMM_internal_restr.R
> +                            numReps = 3, usedApply = getApply(FALSE)[[1]]){
Food for thought: the argument `usedApply` is not used anywhere. It could be deleted, but thinking about possible future developments it may be best to left it there.

2021-04-27 18:03 UTC, alexARC26 commented on R/FMM_internal_restr.R
> +    step1 <- t(apply(grid,1,step1FMM, vData=vData, timePoints=timePoints))
Use `usedApply`.

2021-04-27 18:03 UTC, alexARC26 commented on R/FMM_internal_restr.R
> +    antBestPar <- bestPar
Better name: `previousBestPar` or something like that.

2021-04-27 18:03 UTC, alexARC26 commented on R/FMM_internal_restr.R
> +      suppressWarnings(
Tomorrow, we should talk about this `suppressWarnings`.

2021-04-27 18:03 UTC, alexARC26 commented on R/FMM_internal_restr.R
> +iterateOmegaGrid <- function(vData, omegasIter, betaRestrictions, timePoints = seqTimes(length(vData)),
Argument `stopFunction` should be added and passed to `backfittingRestr`.

2021-04-28 11:56 UTC, christianco97 reviewed
* Alpha and omega grid checks finally deleted, they were not necessary.
* Warnings supressed.
* Requested changes done.
* Pending: check model fitting results. @alexARC26.

2021-04-28 15:49 UTC, alexARC26 commented
Pending:

- [ ] General check of the code, by @christianco97 .
- [ ] Check model fitting results, by @alexARC26 .

2021-04-30 08:08 UTC, merged